perf(images): use multi-stage to reduce populate_jail image size
nebius/soperator pull request #151
Opened 2024-10-29 15:47 UTC by CrackedPoly

After using multiple stages in docker build, we can reduce populate_jail image from ~20G to ~10G.

You should merge this as the size is laaaaarge.

2024-10-29 15:58 UTC, asteny requested changes
Hello! Thanks for your contribution. Please fix comment and lets merge it. I changed the branch to dev, because we have release process based on dev branch. We collecting changes in dev branch and then merge them all in main and build stable version of soperator. So, you changes will be in next release.

2024-10-29 15:58 UTC, asteny commented on images/populate_jail/populate_jail.dockerfile
> +# Frist stage: untap jail_rootfs.tar
First

2024-10-30 03:06 UTC, CrackedPoly commented on images/populate_jail/populate_jail.dockerfile
> +# Frist stage: untap jail_rootfs.tar
Done.

2024-10-30 08:26 UTC, asteny approved these changes

2024-10-30 08:27 UTC, merged